[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ConGoL"
version = "0.1.0"
requires-python = ">= 3.10"
dependencies = [
    "pandas==2.0.3",
]

[project.optional-dependencies]
dev = [
    "pytest",
]